Fix a TypeError in debug statement
The debug statement that was added to print the redirect URLs fails in
production with the following error:

TypeError: can only concatenate str (not "ParseResult") to str

`geturl` returns the URL as a str, which we can then concatenate with
the debug statement.